### PR TITLE
Revert PlatformLayouts to remove unused code

### PR DESCRIPTION
**Pull request by keithc-ca**
It previously declared nested types AIX, SysVPPC64le and SysVS390x which were never used.

Notice that this targets the openj9-staging branch. I considered requesting this be included in #121, but thought it worth separating. This is similar to https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/15, but SysVPPC64le and SysVS390x were removed earlier in those streams.

### CODE REVIEW

**Comment by pshipton** [comment]
We're not going to run acceptance testing atm, just 0.43 testing. This might as well target the openj9 branch, or it can wait in staging until we get the 21.0.3+1 level.

**Comment by keithc-ca** [comment]
Targeting the openj9 branch might create a merge conflict with #121: There's no rush, this can wait.

**Comment by pshipton** [comment]
Setting as draft until after I promote the staging branch in the head stream.

**Comment by pshipton** [comment]
I've pushed 21.0.2 to the openj9 branch. This can target openj9 now if you like.

**Comment by keithc-ca** [comment]
> This can target openj9 now if you like.

Done.

**Review by JasonFengJ9 — APPROVED** [review]

**Pull request merged**
