### PR TITLE
Fix -Djdk.reflect.useDirectMethodHandle=false

### PR DESCRIPTION
**Pull request by babsingh**
See https://github.com/eclipse-openj9/openj9/issues/20155 for more details on the failure and the fix.

Fixes: https://github.com/eclipse-openj9/openj9/issues/20155

### CODE REVIEW

**Comment by babsingh** [comment]
@gacholio Can you review this change?

fyi @r30shah @tajila

**Comment by gacholio** [comment]
jenkins line endings check

**Review by gacholio — APPROVED** [review]
Approved

**Comment by babsingh** [comment]
jdk8 build will probably fail with jdk21 extension repo. To be safe, relaunching the build:

jenkins test sanity zlinux jdk21

**Comment by babsingh** [comment]
jenkins test sanity zlinux jdk21

**Comment by babsingh** [comment]
Github GUI is not updating. Here is the latest PR build: https://openj9-jenkins.osuosl.org/job/Build_JDK21_s390x_linux_Personal/337.

**Comment by gacholio** [comment]
> jdk8 build will probably fail with jdk21 extension repo. To be safe, relaunching the build:

Right, didn't read close enough.

**Comment by gacholio** [comment]
Failure looks infra-related. Do builds even work in this repo?

**Comment by babsingh** [comment]
The [build](https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDK21/82) worked. There are only two identical failures, but they occur in the GC and are unrelated to this change. The below failures are known and documented in https://github.com/eclipse-openj9/openj9/issues/20150.

- `J9vmTest_3`: https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/203/consoleFull
```
14:07:31  +++ j9vm.test.jni.CriticalRegionTest: +++
14:07:31  command: /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/jdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -classpath /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/../../testDependency/lib/asm-all.jar j9vm.test.jni.CriticalRegionTest 
14:07:31  
14:07:44  Unhandled exception
14:07:44  Type=Segmentation error vmState=0x00020002
14:07:44  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=182ed670 Signal_Code=00000001
14:07:44  Handler1=000003FF8B24BA58 Handler2=000003FF8B131A60 InaccessibleAddress=0000000000000000
14:07:44  gpr0=0000000000000110 gpr1=0000000099669966 gpr2=000003FF8408F440 gpr3=000003FF180040D8
14:07:44  gpr4=000003FF00000003 gpr5=0000000000000001 gpr6=000003FF7DA08000 gpr7=0000000000000000
14:07:44  gpr8=000003FF180040D8 gpr9=0000000000000001 gpr10=000003FF8408F440 gpr11=000003FF7DA08000
14:07:44  gpr12=000003FF8BC19000 gpr13=000003FF89BFA890 gpr14=000003FF89A16E04 gpr15=000003FF8B57E7F0
14:07:44  psw=000003FF89A14EFC mask=0705200180000000 fpc=0008fe00 bea=000003FF89A16DFE
14:07:44  fpr0=000003ff8b57e888 (f: 2337794304.000000, d: 2.171957e-311)
14:07:44  fpr1=411ffac000000000 (f: 0.000000, d: 5.239520e+05)
14:07:44  fpr2=0000000000000000 (f: 0.000000, d: 0.000000e+00)
14:07:44  fpr3=3b8cd39300000000 (f: 0.000000, d: 7.630301e-22)
14:07:44  fpr4=411ffac000000000 (f: 0.000000, d: 5.239520e+05)
14:07:44  fpr5=3e92499600000000 (f: 0.000000, d: 2.725042e-07)
14:07:44  fpr6=0000000000000000 (f: 0.000000, d: 0.000000e+00)
14:07:44  fpr7=3e3a33dc00000000 (f: 0.000000, d: 6.100763e-09)
14:07:44  fpr8=000003ff89a51fd8 (f: 2309300224.000000, d: 2.171943e-311)
14:07:44  fpr9=000003ff94260740 (f: 2485520128.000000, d: 2.172030e-311)
14:07:44  fpr10=000003ff8be72148 (f: 2347180288.000000, d: 2.171961e-311)
14:07:44  fpr11=000003ff9bbf2858 (f: 2612996096.000000, d: 2.172093e-311)
14:07:44  fpr12=000621effaf197e7 (f: 4210137088.000000, d: 8.528386e-309)
14:07:44  fpr13=000003ff9456d268 (f: 2488717824.000000, d: 2.172031e-311)
14:07:44  fpr14=000003fff1ef6ed4 (f: 4059000576.000000, d: 2.172807e-311)
14:07:44  fpr15=000003ff9456d338 (f: 2488718080.000000, d: 2.172031e-311)
14:07:44  Module=/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/jdkbinary/j2sdk-image/lib/default/libj9gc_full29.so
14:07:44  Module_base_address=000003FF89900000
14:07:44  Target=2_90_20240912_337 (Linux 3.10.0-1160.118.1.el7.s390x)
14:07:44  CPU=s390x (4 logical CPUs) (0x1ec1b1000 RAM)
14:07:44  ----------- Stack Backtrace -----------
14:07:44  _ZN22MM_GlobalMarkingScheme10scanObjectEP19MM_EnvironmentVLHGCP8J9ObjectNS_10ScanReasonE+0x4c (0x000003FF89A14EFC [libj9gc_full29.so+0x114efc])
14:07:44  _ZN22MM_GlobalMarkingScheme19markLiveObjectsScanEP19MM_EnvironmentVLHGC+0x84 (0x000003FF89A16E04 [libj9gc_full29.so+0x116e04])
14:07:44  _ZN25MM_ParallelGlobalMarkTask3runEP18MM_EnvironmentBase+0x1e8 (0x000003FF89A183B0 [libj9gc_full29.so+0x1183b0])
14:07:44  _ZN21MM_ParallelDispatcher16workerEntryPointEP18MM_EnvironmentBase+0x22e (0x000003FF89A53896 [libj9gc_full29.so+0x153896])
14:07:44  _Z23dispatcher_thread_proc2P14OMRPortLibraryPv+0x138 (0x000003FF89A52398 [libj9gc_full29.so+0x152398])
14:07:44  omrsig_protect+0x3d8 (0x000003FF8B132BB0 [libj9prt29.so+0x32bb0])
14:07:44  dispatcher_thread_proc+0x5c (0x000003FF89A52034 [libj9gc_full29.so+0x152034])
14:07:44  thread_wrapper+0xf6 (0x000003FF8B088A46 [libj9thr29.so+0x8a46])
14:07:44  start_thread+0xea (0x000003FF8BC08312 [libpthread.so.0+0x8312])
14:07:44   (0x000003FF8BA8E232 [libc.so.6+0x10e232])
14:07:44  ---------------------------------------
14:07:44  JVMDUMP039I Processing dump event "gpf", detail "" at 2024/09/12 14:07:44 - please wait.
14:07:44  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/output_1726161321260/J9vmTest_3/core.20240912.140744.57643.0001.dmp' in response to an event
14:07:51  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/output_1726161321260/J9vmTest_3/core.20240912.140744.57643.0001.dmp
14:07:51  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_0/aqa-tests/TKG/output_1726161321260/J9vmTest_3/javacore.20240912.140744.57643.0002.txt' in response to an event
...
14:07:51  JVMDUMP013I Processed dump event "gpf", detail "".
14:07:51  non-zero exit value: 255
14:07:51  *** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

- `J9vmTest_4`: https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_1/203/consoleFull
```
14:06:30  +++ j9vm.test.jni.CriticalRegionTest: +++
14:06:30  command: /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_1/jdkbinary/j2sdk-image/bin/java  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m -classpath /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_1/../../testDependency/lib/asm-all.jar j9vm.test.jni.CriticalRegionTest 
14:06:30  
14:06:43  18:06:43.178 0x1aeb700    j9mm.316    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK21_s390x_linux_Personal/openj9/runtime/gc_vlhgc/GlobalMarkingScheme.cpp:957: ((uintptr_t)0x99669966 == (clazz)->eyecatcher)
14:06:43  JVMDUMP039I Processing dump event "traceassert", detail "" at 2024/09/12 18:06:43 - please wait.
14:06:43  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal_testList_1/aqa-tests/TKG/output_17261616033831/J9vmTest_4/core.20240912.180643.1352830.0001.dmp' in response to an event
...
14:07:06  JVMDUMP013I Processed dump event "traceassert", detail "".
14:07:06  non-zero exit value: 255
14:07:06  *** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by gacholio** [comment]
I do not have permission to merge this.

**Comment by babsingh** [comment]
++ @AdamBrousseau

**Comment by babsingh** [comment]
@gacholio You should be able to merge now. @AdamBrousseau has granted you the needed permissions.

**Pull request merged**
