### PR TITLE
Update FIPS140-3 exclusions with Windows

### PR DESCRIPTION
**Pull request by JinhangZhang**
Add failures shows up in the windows platform.

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@jasonkatonica @llxia FYI

**Comment by keithc-ca** [comment]
A change for https://github.com/ibmruntimes/openj9-openjdk-jdk23 should be merged before this.

**Comment by JinhangZhang** [comment]
Hi @keithc-ca , https://github.com/ibmruntimes/openj9-openjdk-jdk23/commit/cc07586fda7eaa018a3e717d7495dcca274aa7e9 has already been merged

**Comment by keithc-ca** [comment]
It will greatly expedite the process of merging changes if relationships with existing pull requests are highlighted as the change is proposed, rather that expect reviewers to guess or have to explicitly request that information.

**Review by keithc-ca — APPROVED** [review]

**Comment by llxia** [comment]
Please cherry pick this into v0.48.0-release release branch. Thanks

**Comment by keithc-ca** [comment]
> Please cherry pick this into v0.48.0-release branch. Thanks

We have just been advancing the release branch thus far, so no separate pull request will be needed.

**Pull request merged**
