### PR TITLE
Fix typo in reference to NativeECKeyPairGenerator

### PR DESCRIPTION
**Pull request by keithc-ca**
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/783/files#r1588208020.

### CODE REVIEW

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
jenkins copyright check

**Comment by JasonFengJ9** [comment]
jenkins test sanity amac jdk21

**Comment by pshipton** [comment]
You might notice the annoucement on Slack that xlinux, plinux, amac, xmac don't support compile and test atm.

**Comment by JasonFengJ9** [comment]
> That is because the artifactory server at UNB is down, building on plinux, xlinux, amac, xmac is not supported atm.

Okay, as long as the JDK build succeeds, the test is not very useful for this PR which depends on the artifactory.

**Comment by JasonFengJ9** [comment]
```
16:07:01  Executing command: /bin/sh -c git log --pretty=format:%s -1
16:07:04  [consumer_0] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK21_aarch64_mac_Personal/99/OpenJ9-JDK21-aarch64_mac-20240503-055157.tar.gz
16:07:08  [consumer_1] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK21_aarch64_mac_Personal/99/test-images.tar.gz
16:07:12  [consumer_2] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK21_aarch64_mac_Personal/99/debug-image.tar.gz
```
The build succeeded which is sufficient for this PR.

**Pull request merged**
