### PR TITLE
Exclude list for strict profile in FIPS140-3

### PR DESCRIPTION
**Pull request by JinhangZhang**
Adding tests to be ignored for FIPS140-3 strict profile.

@jasonkatonica FYI

### CODE REVIEW

**Comment by JinhangZhang** [comment]
@keithc-ca please help to review

**Comment by keithc-ca** [comment]
Please provide more context to interpret these changes. How do they relate to changes for new versions?

**Comment by keithc-ca** [comment]
Ping @JinhangZhang.

**Comment by JinhangZhang** [comment]
Update the content, remove failures caused by `Agent communication` mentioned at https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/61.

**Pull request merged**
