### PR TITLE
Add JFR JPP flag

### PR DESCRIPTION
**Pull request by thallium**
Depends on https://github.com/eclipse-openj9/openj9/pull/19917.

### CODE REVIEW

**Comment by thallium** [comment]
@tajila FYI

**Comment by tajila** [comment]
The first PR should be created in the jdknext repo

**Comment by thallium** [comment]
> The first PR should be created in the jdknext repo

PR in jdknext repo: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/817

**Comment by keithc-ca** [comment]
Please create changes for [jdk23](https://github.com/ibmruntimes/openj9-openjdk-jdk23) and [jdk22](https://github.com/ibmruntimes/openj9-openjdk-jdk22) which should be merged before this is considered.

**Comment by thallium** [comment]
JDK22 PR: https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/88
JDK23 PR: https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/23

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
