### PR TITLE
Disable use of method handles for core reflection

### PR DESCRIPTION
**Pull request by r30shah**

### CODE REVIEW

**Comment by r30shah** [comment]
@tajila  @keithc-ca  Can I get your review on this PR ? 

FYI @joransiu  / @vijaysun-omr

**Comment by keithc-ca** [comment]
Please provide a description supporting this change. Unless not appropriate (with good, documented reasons), this should first be proposed for the head stream, then Java 23, and only after those are merged, then should this be considered.

**Comment by r30shah** [comment]
I am going to summarize my observations with analyzing performance on one of the enterprise java workload with JDK21 here for reference. 

In [JEP 416](https://openjdk.org/jeps/416) core reflection was re-implemented with Method Handles with the purpose of simplifying adding new language features. If your application relies on reflection to access the fields, then with the use of method handles in core reflection API with JEP416, I observe some of the large enterprise based application was seeing  impact on throughput performance as direct method handle code introduces additional code to be executed at runtime to ensure the accessibility of the the field by the caller.  Proposing this change while OpenJ9 JIT compiler team works on closing the gap with use of Direct Method Handle for reflection. 

I am going to defer to @tajila for the decision on getting this change to JDK23 first.

**Comment by keithc-ca** [comment]
> getting this change to JDK23 first

Jdk23 would be second, https://github.com/ibmruntimes/openj9-openjdk-jdk would be first.

**Comment by r30shah** [comment]
> This change can probably be done in openj9 System::ensureProperties.

I see, closing this PR, I have prepared WIP change (https://github.com/r30shah/openj9/commit/3dc041db1153911462e24722398a1712e241bc1b) to do this in OpenJ9. Currently testing the change.

**Pull request closed without merging**
