### PR TITLE
Clear vmthread from thread object at shutdown

### PR DESCRIPTION
**Pull request by tajila**
Related to: eclipse-openj9/openj9#16659

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Comment by JasonFengJ9** [comment]
Just note that the headstream PR https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/679 is blocked by other issues.

**Comment by JasonFengJ9** [comment]
@tajila please create JDK 8/11/17 PRs.

**Pull request merged**
