### PR TITLE
Enable vm.continuations flag

### PR DESCRIPTION
**Pull request by fengxue-IS**
Depends on https://github.com/adoptium/aqa-tests/pull/4737 and https://github.com/adoptium/aqa-tests/pull/4738
Related: https://github.com/eclipse-openj9/openj9/issues/18037

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
Launched [an internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34648/) since PR build doesn't pick up test change as per 
* https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/506

**Comment by JasonFengJ9** [comment]
The grinder passed which is sufficient to verify the change itself.

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by keithc-ca** [comment]
@JasonFengJ9 This should have waited until after https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/654 was merged.

**Comment by JasonFengJ9** [comment]
Yeah, I was too eager to launch a JDK21 verification build against a few latest changes.

**Pull request closed without merging**
