### PR TITLE
Set scoped value bindings for newly-created thread

### PR DESCRIPTION
**Pull request by thallium**
Related:
- https://github.com/eclipse-openj9/openj9/pull/17402 
- https://github.com/eclipse-openj9/openj9/issues/16677

### CODE REVIEW

**Comment by thallium** [comment]
@babsingh FYI

**Comment by babsingh** [comment]
@JasonFengJ9 @tajila This is the JDK21 backport of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/649. 

@thallium Please update the year in the IBM copyright to 2023 to fix the failing copyright check.

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Comment by JasonFengJ9** [comment]
Jenkins test sanity amac jdk21

**Pull request merged**
