### PR TITLE
Force global GC in ReferencedKeyTest

### PR DESCRIPTION
**Pull request by tajila**
Fixes: https://github.com/eclipse-openj9/openj9/issues/17910

### CODE REVIEW

**Comment by tajila** [comment]
jenkins compile zlinux jdk21

**Comment by tajila** [comment]
jenkins test sanity zlinux jdk21

**Comment by JasonFengJ9** [comment]
jenkins compile zlinux jdk21

**Comment by JasonFengJ9** [comment]
Launched [an internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/17690/)

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
jenkins compile zlinux jdk21

**Comment by pshipton** [comment]
Much more efficient to run a grinder on the test with this test only change. We don't need to build a new JVM.

3 x 100x exit on fail https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2752/

**Comment by pshipton** [comment]
I've also stopped all the other OpenJ9 running builds.

**Comment by pshipton** [comment]
There was one failure in 300 in the grinder.
https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/344/testReport/junit/java_lang_runtime_ReferencedKeyTest/java/ReferencedKeyTest/

**Comment by tajila** [comment]
> There was one failure in 298 in the grinder.

Is that less frequent than before?

**Comment by pshipton** [comment]
Yes. I've been running grinders that exit on the first failure, but you can see the previous numbers in https://github.com/eclipse-openj9/openj9/issues/17910#issuecomment-1665670560. Less frequent is good, but never getting a failure would be better.

**Comment by tajila** [comment]
> Yes. I've been running grinders that exit on the first failure, but you can see the previous numbers in https://github.com/eclipse-openj9/openj9/issues/17910#issuecomment-1665670560. Less frequent is good, but never getting a failure would be better.

Thanks, just wanted to understand if the changes had an impact.

**Comment by tajila** [comment]
Trying again with explicit finalization https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2848/

**Comment by tajila** [comment]
Test passes with latest changes.

@JasonFengJ9 Please review/merge

**Comment by JasonFengJ9** [comment]
@tajila please update the headstream as well.
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/647

**Comment by tajila** [comment]
> @tajila please update the headstream as well.

Done

**Comment by pshipton** [comment]
Pls forward port this as well.

**Comment by tajila** [comment]
Im seeing if we can fix it a different way, https://github.com/eclipse-openj9/openj9/pull/18044

**Pull request closed without merging**
