### PR TITLE
Merge latest openjdk master

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Resolved conflicts:
```
	src/java.base/share/classes/java/lang/Thread.java
	src/java.base/share/classes/java/lang/foreign/AddressLayout.java
	src/java.base/share/classes/java/lang/foreign/Arena.java
	src/java.base/share/classes/java/lang/foreign/FunctionDescriptor.java
	src/java.base/share/classes/java/lang/foreign/Linker.java
	src/java.base/share/classes/java/lang/foreign/MemoryLayout.java
	src/java.base/share/classes/java/lang/foreign/MemorySegment.java
	src/java.base/share/classes/java/lang/foreign/SymbolLookup.java
	src/java.base/share/classes/java/lang/foreign/ValueLayout.java
	src/java.base/share/classes/java/lang/foreign/package-info.java
	src/java.base/share/classes/java/lang/foreign/snippet-files/Snippets.java
	src/java.base/share/classes/java/util/LinkedHashMap.java
	src/java.base/share/classes/jdk/internal/classfile/ClassHierarchyResolver.java
	src/java.base/share/classes/jdk/internal/classfile/impl/ClassHierarchyImpl.java
	src/java.base/share/classes/jdk/internal/classfile/impl/Options.java
	src/java.base/share/classes/jdk/internal/classfile/impl/Util.java
	src/java.base/share/classes/jdk/internal/classfile/impl/verifier/VerifierImpl.java
	src/java.base/share/classes/jdk/internal/classfile/snippet-files/PackageSnippets.java
	src/java.base/share/classes/jdk/internal/foreign/AbstractMemorySegmentImpl.java
	src/java.base/share/classes/jdk/internal/foreign/Utils.java
	src/java.base/share/classes/jdk/internal/foreign/abi/AbstractLinker.java
	src/java.base/share/classes/jdk/internal/foreign/abi/LinkerOptions.java
	src/java.base/share/classes/jdk/internal/foreign/abi/SharedUtils.java
	src/java.base/share/classes/jdk/internal/foreign/abi/fallback/FFIStatus.java
	src/java.base/share/classes/jdk/internal/foreign/abi/fallback/FallbackLinker.java
	src/java.base/share/classes/jdk/internal/foreign/abi/fallback/LibFallback.java
	src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/ABIv2CallArranger.java
	src/java.base/share/classes/jdk/internal/foreign/layout/SequenceLayoutImpl.java
	src/java.base/share/classes/jdk/internal/javac/PreviewFeature.java
	src/java.base/share/classes/sun/security/util/SafeDHParameterSpec.java
	src/java.base/share/native/libfallbackLinker/fallbackLinker.c
	src/java.base/share/native/libfdlibm/s_fabs.c
	src/java.base/share/native/libjava/ForeignLinkerSupport.c
	src/jdk.compiler/share/classes/com/sun/tools/javac/jvm/ClassReader.java
	src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java
	src/jdk.crypto.cryptoki/share/native/libj2pkcs11/p11_util.c
	src/jdk.incubator.concurrent/share/classes/jdk/incubator/concurrent/StructuredTaskScope.java
	src/jdk.jfr/share/classes/jdk/jfr/internal/periodic/JavaEventTask.java
	src/jdk.jfr/share/classes/jdk/jfr/internal/util/ValueFormatter.java
	test/hotspot/jtreg/ProblemList-zgc.txt
	test/hotspot/jtreg/runtime/cds/appcds/test-classes/OldClassWithjsrApp.jasm
	test/hotspot/jtreg/vmTestbase/nsk/share/gc/lock/malloc/libMallocLocker.cpp
	test/jdk/ProblemList-Virtual.txt
	test/jdk/ProblemList.txt
	test/jdk/com/sun/jdi/RedefineNestmateAttr/TestNestmateAttr.java
	test/jdk/java/foreign/StdLibTest.java
	test/jdk/java/foreign/TestDereferencePath.java
	test/jdk/java/foreign/TestIllegalLink.java
	test/jdk/java/foreign/TestLayoutPaths.java
	test/jdk/java/foreign/TestLayouts.java
	test/jdk/java/foreign/TestMemoryAccessInstance.java
	test/jdk/java/foreign/TestSegmentCopy.java
	test/jdk/java/foreign/TestSlices.java
	test/jdk/java/foreign/TestVarArgs.java
	test/jdk/java/io/File/libGetXSpace.c
	test/jdk/java/lang/Class/UnnamedClass/Unnamed.java
	test/jdk/java/lang/ScopedValue/ManyBindings.java
	test/jdk/java/lang/ScopedValue/ScopedValueAPI.java
	test/jdk/java/lang/ScopedValue/StressStackOverflow.java
	test/jdk/java/lang/invoke/VarHandles/describeConstable/p/C.java
	test/jdk/java/util/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java
	test/jdk/java/util/concurrent/StructuredTaskScope/WithScopedValue.java
	test/jdk/jdk/classfile/AdvancedTransformationsTest.java
	test/jdk/jdk/classfile/ClassHierarchyInfoTest.java
	test/jdk/jdk/classfile/UtilTest.java
	test/jdk/jdk/classfile/VerifierSelfTest.java
	test/jdk/jdk/classfile/testdata/Pattern3.java
	test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredTaskScopeTest.java
	test/jdk/jdk/internal/misc/ThreadFlock/WithScopedValue.java
	test/langtools/tools/javac/patterns/Domination.out
	test/langtools/tools/javac/patterns/NewCaseStructureTest.java
	test/langtools/tools/javac/processing/model/element/TestUnnamedClass.java
	test/micro/org/openjdk/bench/vm/compiler/InterfaceCalls.java
```

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
I think this should target the openj9-staging branch (not master); please correct that.

**Comment by keithc-ca** [comment]
If this is intended only to advance the master branch, I would not expect any conflicts.

**Comment by JasonFengJ9** [comment]
> If this is intended only to advance the master branch, I would not expect any conflicts.

This occurs after openjdk jdk21 branching, I don't expect similar conflicts afterwards.

**Comment by keithc-ca** [comment]
There a many, many duplicate commits. The duplication seems to begin with 3f7413c4ac9320f58fec2ee96f3e8d407b39f264 which has identical content to a5cc4338776548666437786454b215e421089386. Those commits have the same parent: 848bef7dc8ff96c7d4f3108a707378b13a788f3e, but 3f7413c4ac9320f58fec2ee96f3e8d407b39f264 and its decedents are only present in the branch proposed for merging here. We should aim to avoid any unnecessary duplication.

**Comment by keithc-ca** [comment]
I think you propose the desired content for the main branch, but the existing tags would not be on the master branch if we force-push the branch.

Looking more closely at the two commits I mentioned above, we can see that they differ only with respect the "Backport-of:" lines of the messages:
```
$ git cat-file commit a5cc4338776548666437786454b215e421089386
tree 9d91d5f1cc989d6d53e730c1fd5edfdf6e1b2fe5
parent 848bef7dc8ff96c7d4f3108a707378b13a788f3e
author Brent Christian <bchristi@openjdk.org> 1670958464 +0000
committer Brent Christian <bchristi@openjdk.org> 1670958464 +0000

8295857: Clarify that cleanup code can be skipped when the JVM terminates (e.g. when calling halt())

Reviewed-by: iris
Backport-of: 304fe34f6b7c483f2b29769096f5032dacc66a6a
```
```
$ git cat-file commit 3f7413c4ac9320f58fec2ee96f3e8d407b39f264
tree 9d91d5f1cc989d6d53e730c1fd5edfdf6e1b2fe5
parent 848bef7dc8ff96c7d4f3108a707378b13a788f3e
author Brent Christian <bchristi@openjdk.org> 1670958464 +0000
committer Brent Christian <bchristi@openjdk.org> 1670958464 +0000

8295857: Clarify that cleanup code can be skipped when the JVM terminates (e.g. when calling halt())

Reviewed-by: iris
Backport-of: c7aca73177339f931f7dfb6627365548a32874f7
```
Perhaps the (commit) duplication is unavoidable at this stage.

Instead, I propose we simply create two merge commits; one reconciling the sequence of duplicate commits, the other merging in newer changes. There are no conflicts to be resolved using that strategy.

In detail:
* start with the tip of the existing master branch
* create a commit that merges 3d67872d558cf692a66b7deb8f44a971e7960b6c
* create a second commit that merges cc09b8a9bbce074972ebb3d2a361733caf7ac005

The result is a tree with the same content as you propose, but keeping the existing tags on the master branch. See #4.

**Comment by JasonFengJ9** [comment]
> but the existing tags would not be on the master branch if we force-push the branch.

Only JDK21 tags are kept, all others are removed as discussed.

In general, I agree merging commits are preferred over a force-push, closing this to favour #4

**Pull request closed without merging**
